/**
 * @kwonlabs/openzl-wasm
 * TypeScript wrapper for Meta's OpenZL compression library.
 */

export interface OpenZLModule {
    version(): string;
    compress(data: Uint8Array): Uint8Array;
    decompress(data: Uint8Array): Uint8Array;
}

// Emscripten generated module type
export interface OpenZLWasmModule {
    version(): string;
    compress(data: Uint8Array): Uint8Array;
    decompress(data: Uint8Array): Uint8Array;
}

let wasmModule: OpenZLWasmModule | null = null;

/**
 * Initializes the OpenZL WASM module.
 * In a real implementation, this would handle the asynchronous loading
 * generated by Emscripten (modularize).
 */
export async function init(moduleFactory: any): Promise<void> {
    wasmModule = await moduleFactory();
}

/**
 * Returns the version of the OpenZL library.
 */
export function getVersion(): string {
    if (!wasmModule) throw new Error("OpenZL module not initialized. Call init() first.");
    return wasmModule.version();
}

/**
 * Compresses the input data.
 */
export function compress(data: Uint8Array): Uint8Array {
    if (!wasmModule) throw new Error("OpenZL module not initialized. Call init() first.");
    return wasmModule.compress(data);
}

/**
 * Decompresses the input data.
 */
export function decompress(data: Uint8Array): Uint8Array {
    if (!wasmModule) throw new Error("OpenZL module not initialized. Call init() first.");
    return wasmModule.decompress(data);
}

// Default export for ease of use
export default {
    init,
    getVersion,
    compress,
    decompress
};